### ISSUE TITLE
Lista de ordenes: Mejora visual

### ISSUE THREAD

**Issue by saintplay** [gonzalesc/wp-culqi-integration#1]
Hola! gracias por crear este plugin!

<img width="1050" alt="Screen Shot 2020-09-19 at 00 00 05" src="https://user-images.githubusercontent.com/9372893/93659502-6c7df600-fa0b-11ea-9c3b-0a0cc9b8647b.png">

He notado que el método de pago no aparece en la lista de órdenes cuando se paga con este plugin

**Comment by gonzalesc** [comment]
Hola @saintplay 
Decime, esto te sale recien con la actualización de WooCommerce? o siempre te ha salido así?

Saludos

**Comment by saintplay** [comment]
Hola, mi versión de Woocomerce es v4.4.1 (no pude probar con las versiones anteriores si funciona bien)
y mi versión del plugin es v1.5.2

**Comment by gonzalesc** [comment]
Hola.

Hemos estado haciendo pruebas en diferentes webs de prueba, pero hasta ahora todo nos ha ido bien.
![image](https://user-images.githubusercontent.com/2523478/94988855-a50eeb00-0546-11eb-9dfc-9e614f0b2dda.png)

Decime, pudiste probarlo en otras webs y también tuviste el mismo error?

**Comment by saintplay** [comment]
Hola, sí.
Parece que es un problema de una web en particular, cuando se usa un plugin multivendor de woocomerce
