### ISSUE TITLE
Problema con la altura del modal en celulares

### ISSUE THREAD

**Issue by oswaldocfr** [gonzalesc/wp-culqi-integration#2]
Hola, tengo un problema con la altura del modal en celulares ya que mi tema cuenta con un div inferior que uso como tabs, trato de modificar el style desde css en mi tema pero no hay cambios.

<img width="1229" alt="Captura de Pantalla 2021-04-07 a la(s) 6 08 14 p  m" src="https://user-images.githubusercontent.com/4346848/113945732-8e36a300-97cc-11eb-8a18-acd398dd6f8e.png">

**Comment by gonzalesc** [comment]
Hola.
El popup de Culqi es un iframe que no controlamos y sólo invocamos; y lamentablemente no se puede agregar style a ningún iframe en una web,

Lo que te recomiendo es bajar el z-index a tu barra menu y así el popup pueda mostrarse completamente.

Saludos
